%setenv OMP_NUM_THREADS 1
mex -v mx_assemble_sparse.cpp ...
       assemble.cpp ...
       compute_regular_element.cpp ...
       shape_function.cpp ...
       partition_stiffness_mat_n_load_vec.cpp ...
       local_coord_2D.cpp ...
       conductance.cpp ...
       compute_IGFEM_element.cpp ...
       child_element_NBJ.cpp...
       impose_Neumann_BC.cpp ...
       impose_Dirichlet_BC.cpp ...
       supg.cpp ...
       body_source_functions.cpp ...
       -larmadillo -lgfortran % for g++
        %CXXFLAGS="\$CXXFLAGS -fopenmp"
%LDFLAGS="\$LDFLAGS "
%CXX="g++-4.7"  LDXX="g++-4.7" GCC="/usr/bin/g++-4.7"...    
%mex -v -larmadillo -lgfortran assemble_mx.cpp assemble.cpp  COMPFLAGS="/openmp $COMPFLAGS" % for microsoft visual c++ 
%mex -v -larmadillo -lgfortran assemble_mx.cpp assemble.cpp  COMPFLAGS="/Qopenmp $COMPFLAGS" % for intel C++ compiler