close all
clear all
path(path,'../channelFiles')
path(path,'../../NURBS/nurbs_toolbox')
path(path,'../M_channels')
path(path, '../M_geom_toolbox')

channelFile = 'parallel3x3ref.channel';

[channels,designParams] = read_channels(channelFile);
[designParams,channels.designParamNum] ...
        = design_params2channel_params_map(designParams,...
                                           channels);
[fileName,pathName] = uigetfile('*.polygon','Open');                                       
polygonFile = [pathName,fileName];
[channels.polygons, channels.vertexCoords,...
 designParams.vertices2params,...
 restrictedParams.nParams, ...
 restrictedParams.iniVals, ...
 restrictedParams.paramPairs,...
 sideTriangles] ...
    = read_polygon_file(polygonFile);                                       


%
figure
plot_channel_polygons(channels.polygons, ...
                      channels.vertexCoords, ...
                      channels.nurbs, ...
                      designParams, ...
                      true)   


